# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Helper Function for Seasonal SIRI Simulation
#'
#' Testing out a seasonal version instead of a daily timestep version.
aspatial_siri <- function(pop_list, mortality_list, transmission_list, recovery_list, fecundity_list, abundance_threshold, carrying_capacity_list, season) {
    .Call(`_epizootic_aspatial_siri`, pop_list, mortality_list, transmission_list, recovery_list, fecundity_list, abundance_threshold, carrying_capacity_list, season)
}

